color = input("Enter a color:")
Plural_noun = input("Enter a Plural noun:")
celebrity = input("Enter a celebrity:")
print("Rose is "+color)
print(Plural_noun + "are  blue")
print("I hate" + celebrity)
